### ISSUE TITLE
Unable to send event from child to parent

### ISSUE THREAD

**Issue by sinchinpark** [statelyai/xstate-viz#380]
**Description**

calling sendParent() or send({}, {to: parent}) from invoked child machine thrown  Uncaught Error

**Expected Result**

Event fetched in parent machine

**Actual Result**

No event was received in the parent machine

Uncaught Error: Unable to send event to child '#_parent' from service {child}.
    at e.sendTo (interpreter.js:119:17)
    at interpreter.js:739:15
    at r (helpers.js:72:23)

**Reproduction**

[PING - PONG](https://stately.ai/viz/9568bf21-ee19-4b51-aec7-a2dd2fad92f2) example from [xstate official doc](https://xstate.js.org/docs/guides/communication.html#sending-events)

**Additional context**

Browser: Vivaldi 5.3.2679.70 (Stable channel) (chromium-based browser)
OS: Linux (Ubuntu 22.04 LTS)

**Comment by Andarist** [comment]
This is a byproduct of our strategy to evaluate the top-level machines from the code editor. The visualizer in here might actually try to create `fetchService` twice - once as a standalone machine, once as the child of the `app`. The first one throws but the latter works OK:
https://codesandbox.io/s/pedantic-montalcini-v3w2rx?file=/src/index.js

To workaround this issue I recommend wrapping this `fetchMachine` in a factory function, like here:
https://stately.ai/viz/3e0a792e-f3e4-4820-a45e-2fb6374c9978

This is still an issue with the visualizer though and we should revisit fixing this in the future.

**Comment by sinchinpark** [comment]
@Andarist Thnx for your fast reply. BTW the initial link in my first post was incorrect so I fixed it.
